except ValueError as ve:
            #     print(ve)
            #     print("value error")